### ISSUE TITLE
Support of Babel

### ISSUE THREAD

**Issue by voronianski** [valtech-au/jsx-control-statements#1]
Any ideas of this could be used with [Babel transpiler](https://babeljs.io/) and [Babelify](https://github.com/babel/babelify) ?

**Comment by AlexGilleran** [comment]
It should be perfectly possible as long as you run jsx-control-statements _then_ Babelify on the result. I haven't tried it but JSTransform shouldn't break on ES6 statements as far as I'm aware, given that there's already ES6 visitors written for it. Are you seeing problems?

The specifics of how to do this depend on how you're using Babelify (grunt, gulp, manually in the command line?).

**Comment by voronianski** [comment]
@AlexGilleran I'm using npm for building with Babelify and it will be ideal to have one more browserify transformation in package.json.

**Comment by justafish** [comment]
Babel doesn't seem to have any support for custom transformers currently. See https://github.com/babel/babel/issues/603

Currently I use grunt-browserify to transform with jsx-control-statements and then run it through babelify e.g.

```
browserify: {
      options: {
        transform: [ 'jsx-control-statements/browserify', 'babelify' ]
      }
}
```
(Using this PR: #3 )

**Comment by AlexGilleran** [comment]
Have added a babel plugin, need to actually use it in anger to make sure it works ok but this should allow for use of jsx-control-statements without having to have an extra build step! :D

**Comment by AlexGilleran** [comment]
Babel plugin is released :)

**Comment by jimfb** [comment]
Sweet!  Thanks @AlexGilleran!
