### ISSUE TITLE
update babel

### ISSUE THREAD

**Issue by theverything** [valtech-au/jsx-control-statements#12]
The version of babel that you have in your package.json is outdated. It uses a module called `chokidar` which requires the `fsevents` module which will not build correctly on node 4.0.0

**Comment by AlexGilleran** [comment]
Sorry, been in Cuba with very limited internet access - will look at this as soon as I get a chance.

**Comment by AlexGilleran** [comment]
Updated Babel version to 5.8.23 in jsx-control-statements 1.1.2
